/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.ImageIcon;

/**
 *
 * @author Yohanes
 */
public class JFrameLedControl extends javax.swing.JFrame {

    private Socket socket;
    private DataInputStream dataInputStream;
    private OutputStream outputStream;
    private boolean isLedOn;

    private Thread dataReceiveThread = new Thread(new Runnable() {
        @Override
        public void run() {
            while (true) {
                String ledStatus = "";

                try {
                    ledStatus = dataInputStream.readLine();
                } catch (IOException e) {
                    System.err.println("ERROR: " + e.toString());
                }
                
                //System.out.println(ledStatus);
                if (ledStatus.equals("led=0")) {
                    isLedOn = false;
                    System.out.println("Initial LED status: LED Off");
                    jLabelButtonLed.setIcon(new ImageIcon(getClass().
                            getResource("off.png")));
                } else if (ledStatus.equals("led=1")) {
                    isLedOn = true;
                    System.out.println("Initial LED status: LED On");
                    jLabelButtonLed.setIcon(new ImageIcon(getClass().
                            getResource("on.png")));
                }
            }
        }
    });

    /**
     * Creates new form JFrameLedControl
     */
    public JFrameLedControl() {
        initComponents();

        getContentPane().setBackground(Color.WHITE);
        
        try {
            socket = new Socket("127.0.0.1", 23);
            dataInputStream = new DataInputStream(socket.getInputStream());
            outputStream = socket.getOutputStream();
        } catch (UnknownHostException e) {
            System.err.println("ERROR: " + e.toString());
        } catch (IOException e) {
            System.err.println("ERROR: " + e.toString());
        }

        dataReceiveThread.start();
        sendCommand("led=?\n");
    }

    private void sendCommand(String cmd) {
        try {
            outputStream.write(new String(cmd).getBytes());
            outputStream.flush();
        } catch (IOException e) {
            System.err.println("ERROR: " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLedControl = new javax.swing.JPanel();
        jLabelButtonLed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LED Telnet");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ethernet.png")));
        setMaximumSize(new java.awt.Dimension(176, 172));
        setMinimumSize(new java.awt.Dimension(176, 172));
        setResizable(false);

        jPanelLedControl.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLedControl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LED Control via Telnet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        jLabelButtonLed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelButtonLedMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelLedControlLayout = new javax.swing.GroupLayout(jPanelLedControl);
        jPanelLedControl.setLayout(jPanelLedControlLayout);
        jPanelLedControlLayout.setHorizontalGroup(
            jPanelLedControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLedControlLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabelButtonLed, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanelLedControlLayout.setVerticalGroup(
            jPanelLedControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLedControlLayout.createSequentialGroup()
                .addComponent(jLabelButtonLed, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLedControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLedControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonLedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonLedMouseReleased
        if (isLedOn) {
            sendCommand("led=0\n");
            isLedOn = false;
            jLabelButtonLed.setIcon(new ImageIcon(getClass().
                    getResource("off.png")));
        } else {
            sendCommand("led=1\n");
            isLedOn = true;
            jLabelButtonLed.setIcon(new ImageIcon(getClass().
                    getResource("on.png")));
        }
    }//GEN-LAST:event_jLabelButtonLedMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLedControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLedControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLedControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLedControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLedControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelButtonLed;
    private javax.swing.JPanel jPanelLedControl;
    // End of variables declaration//GEN-END:variables
}
